services:
  filebrowser:
    volumes:
      - '/mnt/media:/srv/media'
      - '/mnt/netboot:/srv/netboot'
      - '${HOME}/dockers:/srv/dockers'
      - '${HOME}/dockers/compose/filebrowser/config:/config'
      - '${HOME}/dockers/dockers_data/filebrowser:/database'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${FILEBROWSER_SERVICE}.rule=Host(`${FILEBROWSER_HOST}`)'
      - 'traefik.http.routers.${FILEBROWSER_SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${FILEBROWSER_SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${FILEBROWSER_SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.services.${FILEBROWSER_SERVICE}.loadbalancer.server.port=80'
      - 'traefik.docker.network=traefik_proxy'
    networks:
      traefik_proxy:
    # ports:
    #   - '80:80'
    image: filebrowser/filebrowser
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
