services:
  cronemby:
    build: .
    container_name: cronemby
    networks:
      traefik_proxy:
    environment:
      - emby-domain=https://emby.monib.xyz
      - emby-token=${EMBY_TOKEN}
      - intro-scan-id=${EMBY_INTRO_ID}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${SERVICE}.tls=true'
      - 'traefik.http.routers.${SERVICE}.rule=Host(`${HOST}`) || Host(`${HOST2}`)'
      - 'traefik.http.routers.${SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${SERVICE}.tls.domains[0].main=${HOST}'
      - 'traefik.http.services.${SERVICE}.loadbalancer.server.scheme=https'
      - 'traefik.docker.network=traefik_proxy'
    restart: unless-stopped
networks:
  traefik_proxy:
    external: true
