services:
  traefik:
    image: 'traefik:v3.3.7'
    hostname: 'traefik'
    container_name: 'traefik'
    ports:
      - '192.168.1.22:80:80'
      - '192.168.1.22:443:443'
      - '192.168.1.22:8001:8001'
      - '8000:8000'
      - '4434:4434'
      #- "8080:8080"
    environment:
      - 'CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}'
      - 'CF_API_EMAIL=${CF_API_EMAIL}'
      # This changes the config dir so i can easily put my config in the git repo
      # This doesn't seem to be officially supported so remove if any issues
      - 'XDG_CONFIG_HOME=/config/'
    volumes:
      - '${HOME}/dockers/dockers_data/traefik/config:/etc/traefik'
      - '${HOME}/dockers/compose/traefik/config:/config'
      - '/var/run/docker.sock:/var/run/docker.sock:ro'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${SERVICE}.rule=Host(`${HOST}`)'
      - 'traefik.http.routers.${SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${SERVICE}.service=api@internal'
      - 'traefik.http.routers.${SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.routers.${SERVICE}.middlewares=authelia@docker'
      - 'traefik.docker.network=traefik_proxy'

      - 'traefik.http.middlewares.crowdsec-bar.plugin.bouncer.enabled=true'
      - 'traefik.http.middlewares.crowdsec-bar.plugin.bouncer.crowdsecMode=stream'
      - 'traefik.http.middlewares.crowdsec-bar.plugin.bouncer.crowdsecAppsecEnabled=true'
      - 'traefik.http.middlewares.crowdsec-bar.plugin.bouncer.crowdsecAppsecHost=crowdsec:7422'
      - 'traefik.http.middlewares.crowdsec-bar.plugin.bouncer.crowdsecLapiKey=${CROWDSEC_API_KEY}'

      - 'traefik.http.middlewares.authelia.forwardAuth.address=http://authelia:9091/api/verify?rd=https://${HOST}'
      - 'traefik.http.middlewares.authelia.forwardAuth.trustForwardHeader=true'
      - 'traefik.http.middlewares.authelia.forwardAuth.authResponseHeaders=Remote-User,Remote-Groups,Remote-Name,Remote-Email'
    depends_on:
      - authelia
      - crowdsec
    networks:
      traefik_proxy:
        ipv4_address: 10.0.10.254
    dns:
      - 8.8.8.8
    restart: always

  crowdsec:
    image: crowdsecurity/crowdsec
    container_name: crowdsec
    restart: always
    # ports:
    #   - 127.0.0.1:8080:8080
    environment:
      GID: 1000
      COLLECTIONS: 'crowdsecurity/appsec-virtual-patching crowdsecurity/appsec-generic-rules crowdsecurity/traefik'
      BOUNCER_KEY_TRAEFIK: '${CROWDSEC_API_KEY}'
    networks:
      traefik_proxy:
    volumes:
      - ${HOME}/dockers/dockers_data/crowdsec/db:/var/lib/crowdsec/data/
      - ${HOME}/dockers/dockers_data/crowdsec/config:/etc/crowdsec/
      - ${HOME}/dockers/dockers_data/traefik/config/logs:/var/log/traefik/:ro

  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ${HOME}/dockers/dockers_data/traefik/authelia/db:/db
      - ${HOME}/dockers/compose/traefik/authelia/config:/config
    security_opt:
      - no-new-privileges:true
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.${AUTH_SERVICE}.rule=Host(`${AUTH_HOST}`)'
      - 'traefik.http.routers.${AUTH_SERVICE}.entrypoints=websecure,websecure-public'
      - 'traefik.http.routers.${AUTH_SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${AUTH_SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.services.${AUTH_SERVICE}.loadbalancer.server.port=9091'
    # ports:
    #   - 9091:9091
    networks:
      traefik_proxy:
    user: 1000:1000
    restart: unless-stopped
    # healthcheck:
    #   disable: true

  redis:
    image: redis:alpine
    container_name: redis
    volumes:
      - ${HOME}/dockers/dockers_data/traefik/authelia/redis:/data
    # expose:
    #   - 6379
    networks:
      traefik_proxy:
    depends_on:
      - authelia
    restart: unless-stopped

networks:
  traefik_proxy:
    name: traefik_proxy
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.10.0/24
