
services:
  watchtower:
    container_name: watchtower
    restart: always
    environment:
      WATCHTOWER_SCHEDULE: 0 0 4 * * *
      TZ: Asia/Karachi
      WATCHTOWER_CLEANUP: "true"
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      traefik_proxy:       

networks:
  traefik_proxy:
    external: true

