services:
  boot-server:
    image: lov432/netboot-boot-server:${MENU_VERSION}
    container_name: boot-server
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.${BOOT_SERVICE}.rule=Host(`${BOOT_HOST}`)'
      - 'traefik.http.routers.${BOOT_SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${BOOT_SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${BOOT_SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.services.${BOOT_SERVICE}.loadbalancer.server.port=80'
      - 'traefik.http.routers.${BOOT_SERVICE}.service=${BOOT_SERVICE}'

      - 'traefik.http.routers.${BOOT_SERVICE}-http.rule=Host(`${BOOT_HOST}`)'
      - 'traefik.http.routers.${BOOT_SERVICE}-http.entrypoints=web-pxe'
      - 'traefik.http.routers.${BOOT_SERVICE}-http.service=${BOOT_SERVICE}'

      - 'traefik.docker.network=traefik_proxy'
    networks:
      - traefik_proxy
    ports:
      - 69:69/udp
    restart: unless-stopped

  netbootxyz:
    image: netbootxyz/netbootxyz
    container_name: netbootxyz
    environment:
      - PUID=1000
      - PGID=1000
      - MENU_VERSION=${MENU_VERSION}
      # - PORT_RANGE=30000:30010 #optional
      # - SUBFOLDER=/ #optional
    labels:
      - 'traefik.enable=true'

      - 'traefik.http.routers.${NETBOOT_SERVICE}.rule=Host(`${NETBOOT_HOST}`)'
      - 'traefik.http.routers.${NETBOOT_SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${NETBOOT_SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${NETBOOT_SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.routers.${NETBOOT_SERVICE}.middlewares=authelia@docker'
      - 'traefik.http.services.${NETBOOT_SERVICE}.loadbalancer.server.port=3000'
      - 'traefik.http.routers.${NETBOOT_SERVICE}.service=${NETBOOT_SERVICE}'

      - 'traefik.http.routers.${ASSETS_SERVICE}.rule=Host(`${ASSETS_HOST}`)'
      - 'traefik.http.routers.${ASSETS_SERVICE}.entrypoints=websecure'
      - 'traefik.http.routers.${ASSETS_SERVICE}.tls.certresolver=production'
      - 'traefik.http.routers.${ASSETS_SERVICE}.tls.domains[0].main=*.monib.xyz'
      - 'traefik.http.services.${ASSETS_SERVICE}.loadbalancer.server.port=80'
      - 'traefik.http.routers.${ASSETS_SERVICE}.service=${ASSETS_SERVICE}'

      - 'traefik.http.routers.${ASSETS_SERVICE}-http.rule=Host(`${ASSETS_HOST}`)'
      - 'traefik.http.routers.${ASSETS_SERVICE}-http.entrypoints=web-pxe'
      - 'traefik.http.routers.${ASSETS_SERVICE}-http.service=${ASSETS_SERVICE}'

      - 'traefik.docker.network=traefik_proxy'
    volumes:
      - ${HOME}/dockers/dockers_data/netboot/config:/config
      - /mnt/netboot/assets:/assets
    # ports:
    # - 3000:3000
    # - 69:69/udp
    # - 8080:80 #optional
    networks:
      traefik_proxy:
    restart: unless-stopped

networks:
  traefik_proxy:
    external: true
