services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr
    container_name: sonarr
    hostname: sonarr
    networks:
      traefik_proxy:
      err-apps:
        ipv4_address: 172.1.0.2
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - /mnt/dockers_mount/dockers_data/arr/config/sonarr:/config
      - /mnt/media:/media
      - /mnt/dockers_mount/dockers_backup/arr/sonarr:/Backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${SONARR_SERVICE}.rule=Host(`${SONARR_HOST}`)"
      - "traefik.http.routers.${SONARR_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${SONARR_SERVICE}.tls.certresolver=production"
      - "traefik.http.routers.${SONARR_SERVICE}.tls.domains[0].main=*.monib.xyz"
      - "traefik.http.routers.${SONARR_SERVICE}.middlewares=authelia@docker"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  radarr:
    image: ghcr.io/linuxserver/radarr
    container_name: radarr
    hostname: radarr
    networks:
      traefik_proxy:
      err-apps:
        ipv4_address: 172.1.0.5
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Karachi
    volumes:
      - /mnt/dockers_mount/dockers_data/arr/config/radarr:/config
      - /mnt/media:/media
      - /mnt/dockers_mount/dockers_backup/arr/radarr:/Backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${RADARR_SERVICE}.rule=Host(`${RADARR_HOST}`)"
      - "traefik.http.routers.${RADARR_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${RADARR_SERVICE}.tls.certresolver=production"
      - "traefik.http.routers.${RADARR_SERVICE}.tls.domains[0].main=*.monib.xyz"
      - "traefik.http.routers.${RADARR_SERVICE}.middlewares=authelia@docker"
      - "traefik.docker.network=traefik_proxy"
    restart: unless-stopped

  # flaresolverr:
  #   image: ghcr.io/flaresolverr/flaresolverr:latest
  #   container_name: flaresolverr
  #   environment:
  #     - LOG_LEVEL=info
  #     - LOG_HTML=false
  #     - CAPTCHA_SOLVER=none
  #     - TZ=Europe/London
  #   networks:
  #     err-apps:
  #       ipv4_address: 172.1.0.6
  #   restart: unless-stopped

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /mnt/dockers_mount/dockers_data/arr/config/prowlarr/data:/config
      - /mnt/dockers_mount/dockers_backup/arr/prowlarr:/Backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${PROWLARR_SERVICE}.rule=Host(`${PROWLARR_HOST}`)"
      - "traefik.http.routers.${PROWLARR_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${PROWLARR_SERVICE}.tls.certresolver=production"
      - "traefik.http.routers.${PROWLARR_SERVICE}.tls.domains[0].main=*.monib.xyz"
      - "traefik.http.routers.${PROWLARR_SERVICE}.middlewares=authelia@docker"
      - "traefik.docker.network=traefik_proxy"
    networks:
      traefik_proxy:
      err-apps:
        ipv4_address: 172.1.0.8
    # ports:
    #   - 9696:9696
    restart: unless-stopped

  # qbit:
  #   image: ghcr.io/linuxserver/qbittorrent:latest
  #   container_name: qbit
  #   networks:
  #     err-apps:
  #       ipv4_address: 172.1.0.3
  #     traefik_proxy:
  #   environment:
  #     - PUID=1000
  #     - PGID=1000
  #     - TZ=Asia/Karachi
  #     - WEBUI_PORT=8080
  #     - DOCKER_MODS=arafatamim/linuxserver-io-mod-vuetorrent
  #   volumes:
  #     - /mnt/dockers_mount/dockers_data/arr/config/qbit:/config
  #     - /mnt/media:/media
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.${QBIT_SERVICE}.rule=Host(`${QBIT_HOST}`)"
  #     - "traefik.http.routers.${QBIT_SERVICE}.entrypoints=websecure"
  #     - "traefik.http.routers.${QBIT_SERVICE}.tls.certresolver=production"
  #     - "traefik.http.routers.${QBIT_SERVICE}.tls.domains[0].main=*.monib.xyz"
  #     - "traefik.http.services.${QBIT_SERVICE}.loadbalancer.server.port=8080"
  #     - "traefik.http.routers.${QBIT_SERVICE}.middlewares=cors-allow-www-self@file"
  #     - "traefik.docker.network=traefik_proxy"
  #   ports:
  #     - 50272:50272
  #   restart: unless-stopped

  qbit:
    image: "11notes/qbittorrent:5.1.2"
    container_name: qbit
    read_only: true
    networks:
      err-apps:
        ipv4_address: 172.1.0.3
      traefik_proxy:
    volumes:
      - /mnt/media:/media
      - /mnt/dockers_mount/dockers_data/arr/config/qbittorrent/config:/qbittorrent/etc
      - /mnt/dockers_mount/dockers_data/arr/config/qbittorrent/db:/qbittorrent/var
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${QBIT_SERVICE}.rule=Host(`${QBIT_HOST}`)"
      - "traefik.http.routers.${QBIT_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${QBIT_SERVICE}.tls.certresolver=production"
      - "traefik.http.routers.${QBIT_SERVICE}.tls.domains[0].main=*.monib.xyz"
      - "traefik.http.services.${QBIT_SERVICE}.loadbalancer.server.port=8080"
      - "traefik.http.routers.${QBIT_SERVICE}.middlewares=cors-allow-www-self@file"
      - "traefik.docker.network=traefik_proxy"
    ports:
      - 50272:50272
    healthcheck:
      test: ["NONE"]
    restart: unless-stopped


  jellyseerr:
    image: fallenbagel/jellyseerr:latest
    container_name: jellyseerr
    environment:
      - TZ=Asia/Karachi
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.${JELLYSEERR_SERVICE}.rule=Host(`${JELLYSEERR_HOST}`)"
      - "traefik.http.routers.${JELLYSEERR_SERVICE}.entrypoints=websecure"
      - "traefik.http.routers.${JELLYSEERR_SERVICE}.tls.certresolver=production"
      - "traefik.http.routers.${JELLYSEERR_SERVICE}.tls.domains[0].main=*.monib.xyz"
      - "traefik.http.services.${JELLYSEERR_SERVICE}.loadbalancer.server.port=5055"
      - "traefik.docker.network=traefik_proxy"
    volumes:
      - /mnt/dockers_mount/dockers_data/arr/config/jellyseerr:/app/config
    networks:
      err-apps:
        ipv4_address: 172.1.0.7
      traefik_proxy:
    restart: unless-stopped

  decluttarr:
    image: ghcr.io/manimatter/decluttarr:latest
    container_name: decluttarr
    restart: always
    environment:
      TZ: Asia/Karachi
      PUID: 1000
      PGID: 1000

      ## General
      # TEST_RUN: True
      # SSL_VERIFICATION: False
      LOG_LEVEL: INFO

      ## Features
      REMOVE_TIMER: 5
      REMOVE_FAILED: True
      REMOVE_FAILED_IMPORTS: True
      REMOVE_METADATA_MISSING: False
      REMOVE_MISSING_FILES: False
      REMOVE_ORPHANS: False
      REMOVE_SLOW: False
      REMOVE_STALLED: False
      REMOVE_UNMONITORED: False
      RUN_PERIODIC_RESCANS: ' { "SONARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7}, "RADARR": {"MISSING": true, "CUTOFF_UNMET": true, "MAX_CONCURRENT_SCANS": 3, "MIN_DAYS_BEFORE_RESCAN": 7} }'

      # Feature Settings
      PERMITTED_ATTEMPTS: 2
      NO_STALLED_REMOVAL_QBIT_TAG: Don't Kill
      MIN_DOWNLOAD_SPEED: 100
      FAILED_IMPORT_MESSAGE_PATTERNS: ' [ "Not a Custom Format upgrade for existing", "Not an upgrade for existing", "No files found are eligible for import" ]'

      ## Sonarr
      SONARR_URL: http://sonarr:8989
      SONARR_KEY: ${DECLUTTARR_SONARR_KEY}

      ## qBitorrent
      QBITTORRENT_URL: http://qbit:8080
      QBITTORRENT_USERNAME: ${DECLUTTARR_QBIT_USERNAME}
      QBITTORRENT_PASSWORD: ${DECLUTTARR_QBIT_PASSWORD}

    networks:
      err-apps:
        ipv4_address: 172.1.0.9
      traefik_proxy:

networks:
  err-apps:
    name: err-apps
    driver: bridge
    ipam:
      config:
        - subnet: 172.1.0.0/28
  traefik_proxy:
    external: true

